### ISSUE TITLE
R&D to figure out if section component is reusable

### ISSUE THREAD

**Issue by mimifi** [chingu-voyages/v10-toucans-team-08#15]
- If the section is reusable for simple sections like second and last section

**Comment by mimifi** [comment]
Hey @MichielSlebos, @Saggitarie, 
I think the best way to solve our problem is at first to reduce the scope of our component as much as possible. The only common property for all section is the dimension of each section and that they have all a background image. 
Therefor we should get rid of anything else in our main-section-component. 
We will need some sub component for button, text, additional GIFF or image inside the section. 
I think this could be a good start to make our component reusable. 
After that I think we need some [Property binding] to can change our text or additional images. But I'm not completely sure about it. 

What do you guys think about this idea??

**Comment by Saggitarie** [comment]
Hey Mahtab

I think your idea is good and is worth a try!
Well need to search about property binding to make sure
